### ISSUE TITLE
Consider adding BHoM to Grasshopper Package Manager

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Grasshopper_UI#661]
#### Description:

As [requested by one of the external users](https://www.linkedin.com/feed/update/urn:li:activity:6950569666889056257?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6950569666889056257%2C6950588070786166784%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A6950569666889056257%2C6950717048264003584%29), it would be great to start delivering BHoM via the [Grasshopper Package Manager](https://developer.rhino3d.com/guides/yak/creating-a-grasshopper-plugin-package/). Happy for @FraserGreenroyd to lead this with myself and @al-fisher as support (hands-on and admin, respectively).

@alelom @IsakNaslundBh @adecler FYI

**Comment by timonielsen** [comment]
Thanks for raising this. This feature is quite essential for using BHoM as the framework for tool development. We wish to be able to distribute tools to our engineers, who may not necessarily have the rights (or will) to go and download and install BHoM. It should install automatically when you open a GH-script that uses BHoM. Thanks for the great work you guys do!

**Comment by FraserGreenroyd** [comment]
So I have looked into this during this milestone and unfortunately this does not seem possible for the BHoM to be registered with the Grasshopper/Rhino Package Manager.

The Yak packages up all the DLLs necessary for a `.gha` file, but does not do the same from a `.ghlink` file. Nor does it allow for packaging up directories outside the same directory as the `.gha` file. This means we cannot package up the `Upgrades` folder within `%ProgramData%/BHoM/Upgrades`. When the package is installed via the Rhino package manager, it installs to a new folder `%AppData%\McNeel\Rhinoceros\packages\` (followed by Rhino version e.g. `6.0`). So even if we could package up the `Upgrades`, we would need to change a lot of infrastructure to support relative install paths, which could then break BHoM for other tools, such as Excel, Revit, and Dynamo. Anyone using BHoM for those tools would need to run the MSI installer and would risk having multiple versions of BHoM on their computer.

We could package BHoM for Grasshopper up and exclude the `Upgrades`, and ensure the Target Invocation Error is handled if the folder doesn't exist (which is currently thrown when installing using this method), but we would then lose one of the key components of BHoM workflow and methodology of being able to upgrade scripts when versions change. People using BHoM for Grasshopper via the package manager would lose all of that richness, and scripts made in 6.0 may not work in 6.1 because of changes made without the versioning available.

As such, I do not deem it feasible for this to be explored further as it will require a lot of work for minimal gain - given the ease of using the MSI installer provided on [BHoM.xyz](https://bhom.xyz) each milestone and the complexity of tools/services the BHoM is offering, the risk of introducing a second way to install BHoM which may conflict with BHoM's own installation process is greater than the gain of making it work, particularly when a suitable solution (MSI installer) exists. If the only option to install BHoM was to compile from source then I would argue for doing it, but as it currently stands, this is a lot of work for minimal gain I'm afraid.
